name: syuosyuo_player
description: This is a fan app for the VTuber 秋桜しゅお (Shuōshuo).

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # For Architecture
  flutter_hooks:
  hooks_riverpod:

  # For Model
  riverpod_annotation:
  freezed_annotation:
  json_annotation:

  # For Navigation
  go_router:

  # For UIs
  gap:
  google_fonts:
  youtube_player_iframe:
  pointer_interceptor:
  url_launcher:
  intl:
  responsive_framework:
  carousel_slider:
  flutter_linkify:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner:
  flutter_gen_runner:
  freezed:
  riverpod_generator:
  json_serializable:
  go_router_builder:

flutter_gen:
  output: lib/gen/
  line_length: 100

  fonts:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/license/

fonts:
  - family: SawarabiGothic
    fonts:
      - asset: assets/fonts/SawarabiGothic-Regular.ttf
        style: regular
